configuration: 
  name: helloqa
  author: oaqa
  
persistence-provider:
  inherit: helloqa.db.local-persistence-provider
 
collection-reader: 
   inherit: helloqa.collection.decorated-collection-reader
   dataset: TREC
#   file: /input/info-gain/trec-9-orig-test-t8.txt
#   file: /input/info-gain/trec-9-variants-test-t8.txt
#   file: /input/info-gain/trec-9-rand-test-t8.txt
#   file: /input/trec-8-9-10-questions.txt
   file: /input/TREC-8-Questions.txt
#   file: /input/trec-9-questions.txt
#   file: /input/trec-10-questions.txt
#   file: /input/TREC-8-sample.txt

#collection-reader:
#  inherit: helloqa.collection.decorated-collection-reader
#  dataset: GUTENBERG
#  file: /input/small.txt
#  inherit: fs.dir-collection-reader
#  dataset: GUTENBERG
#  suffix: txt
#  dir: /input

pipeline:
  - inherit: jdbc.sqlite.cse.phase  
    name: answertype-extractor
    options: |
      - inherit: phases.AnswerTypeExtractor

  - inherit: jdbc.sqlite.cse.phase  
    name: keyterm-extractor
    options: |
      - inherit: phases.KeytermExtractor

  - inherit: jdbc.sqlite.cse.phase  
    name: ic-event-extractor
    options: |
      - inherit: phases.ICEventExtractor

  - inherit: jdbc.sqlite.cse.phase  
    name: passage-retrieval
    options: |
      - inherit: phases.PassageRetrieval

  - inherit: jdbc.sqlite.cse.phase  
    name: information-extractor
    options: |
      - inherit: phases.InformationExtractor

  - inherit: jdbc.sqlite.cse.phase  
    name: answer-generator
    options: |
      - inherit: phases.AnswerGenerator
  
 # - inherit: phases.AnswerEvaluation 

    
